[project]
name = "forecast"
version = "0.1.0"
description = "A weather forecast program."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pathlib>=1.0.1",
    "requests>=2.32.3",
]
